language: swift
osx_image: xcode9

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/ProxyResolver.xcworkspace -scheme ProxyResolver-Example -sdk macosx clean build test | xcpretty
- pod lib lint
